@startuml
entity ユーザー {
    + ユーザーID (PK)
    ユーザー名
    メールアドレス
    パスワード
    作成日時
    更新日時
}

entity チャットルーム {
    + ルームID (PK)
    ルーム名
    作成日時
}

entity メッセージ {
    + メッセージID (PK)
    ルームID (FK)
    送信者ユーザーID (FK)
    メッセージ本文
    送信日時
    更新日時
    お気に入り
}

entity ユーザーチャットルーム {
    + ユーザーチャットルームID (PK)
    ユーザーID (FK)
}

ユーザー --|{ ユーザーチャットルーム
チャットルーム --|{ ユーザーチャットルーム
ユーザー --|{ メッセージ
@enduml
